version: '3.8'

####################################
##                                ##
## WARN: DON'T USE IN PRODUCTION! ##
##                                ##
####################################

services:
  app:
    container_name: event-dev
    hostname: event-dev
    volumes:
      - .:/app/
    build:
      dockerfile: ./infra/Dockerfile
      target: dev
      context: .
    env_file:
      - .env
    networks:
      - net_1

  db:
    image: postgres:14
    container_name: postgres-dev
    env_file:
      - .env
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - net_1

volumes:
  database_postgres: 

networks:
  net_1:
    driver: bridge