version: '3.8'

services:
  main:
    container_name: ton-event-idx-dev
    hostname: ton-event-idx-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app/
    ports:
      - '80:80'

networks:
  default: